buildDrafts = false
buildExpired = false
buildFuture = false
cleanDestinationDir = true
disableHugoGeneratorInject = false
disableLiveReload = true

contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "public"
staticDir = "static"
themesDir = "themes"

defaultContentLanguage = "en-gb"
languageCode = "en-gb"
languageName = "English"

enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true
enableRobotsTXT = true

summaryLength = 80

googleAnalytics = "UA-135263577-1"
log = true
watch = false

relativeURLs = true
minify = true

paginate = 10
paginatePath = "page"

[permalinks]
    posts = "/:year/:month/:slug/"