title = "Simon Albrecht"
baseURL = "https://simonalbrecht.ch"

buildDrafts = false
buildExpired = false
buildFuture = false
cleanDestinationDir = true
disableHugoGeneratorInject = false
disableLiveReload = true

googleAnalytics = "UA-135263577-1"

watch = false
minify = true