backend:
  name: github
  repo: simonalbrecht/website
  branch: redesign

publish_mode: editorial_workflow

media_folder: static/uploads
public_folder: uploads

collections:
  - name: 'page'
    label: 'Standalone Page'
    folder: 'content/pages'
    create: true
    identifier_field: 'title'
    fields:
      - label: 'ID'
        name: 'id'
        widget: 'string'
      - label: 'Author'
        name: 'author'
        widget: 'string'
        default: 'Simon Albrecht'
      - label: 'Title'
        name: 'title'
        widget: 'markdown'
      - label: 'Intro'
        name: 'intro'
        widget: 'markdown'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
      - label: 'Links'
        name: 'links'
        required: false
        widget: 'list'
        collapsed: false
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'URL'
            name: 'url'
            widget: 'string'
          - label: 'Icon'
            name: 'icon'
            widget: 'select'
            multiple: false
            options:
              - label: 'Github'
                value: 'github'
              - label: 'LinkedIn'
                value: 'linkedin'
              - label: 'Twitter'
                value: 'twitter'
              - label: 'Instagram'
                value: 'instagram'
              - label: 'Envelope'
                value: 'envelope'
              - label: 'Business Card'
                value: 'business-card'


